<?php

namespace Database\Seeders;

use App\Models\Organization;
use App\Models\User;
use Illuminate\Database\Seeder;

class OrganizationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get the first user to associate with organizations
        $user = User::first();

        if (!$user) {
            $this->command->warn('No users found. Please run UserSeeder first.');
            return;
        }

        $organizations = [
            [
                'ucode' => '0001',
                'user_id' => $user->id,
                'name' => '16 ECB',
                'name_bn' => '১৬ ইসিবি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0002',
                'user_id' => $user->id,
                'name' => '18 T Ward Project',
                'name_bn' => '১৮ টি ওয়ার্ড প্রকল্প',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0003',
                'user_id' => $user->id,
                'name' => '19 ECB',
                'name_bn' => '১৯ ইসিবি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0004',
                'user_id' => $user->id,
                'name' => '24 Engineers (Construction Brigade)',
                'name_bn' => '২৪ ইঞ্জিনিয়ার (নির্মাণ ব্রিগেড)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0005',
                'user_id' => $user->id,
                'name' => '300 Feet to Madani Avenue Project  ',
                'name_bn' => '৩০০ ফুট থেকে মাদানী অ্যাভিনিউ প্রকল্প',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0006',
                'user_id' => $user->id,
                'name' => '24 Engineers- Pipe Line Project',
                'name_bn' => '২৪ ইঞ্জিনিয়ার- পাইপ লাইন প্রকল্প',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0007',
                'user_id' => $user->id,
                'name' => '25 ECB      ',
                'name_bn' => '২৫ ইসিবি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0008',
                'user_id' => $user->id,
                'name' => '34 Engineers (Construction Brigade)',
                'name_bn' => '৩৪ ইঞ্জিনিয়ার (নির্মাণ ব্রিগেড)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0009',
                'user_id' => $user->id,
                'name' => 'Adamjee Cantt College',
                'name_bn' => 'আদমজী ক্যান্ট কলেজ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0010',
                'user_id' => $user->id,
                'name' => 'Adamjee Cantt School',
                'name_bn' => 'আদমজী ক্যান্ট স্কুল',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0011',
                'user_id' => $user->id,
                'name' => 'AFD',
                'name_bn' => 'এএফডি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0012',
                'user_id' => $user->id,
                'name' => 'AGC Spinning Mills',
                'name_bn' => 'এজিসি স্পিনিং মিলস',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0013',
                'user_id' => $user->id,
                'name' => 'AHQ AG Branch (STMK-1)',
                'name_bn' => 'এএইচকিউ এজি শাখা (এসটিএমকে-১)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0015',
                'user_id' => $user->id,
                'name' => 'AHQ Direroate of Welfare and Rehavilitation',
                'name_bn' => 'এএইচকিউ কল্যাণ ও পুনর্বাসন অধিদপ্তর',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0016',
                'user_id' => $user->id,
                'name' => 'AHQ Atomic Protection Cell (NSPC)',
                'name_bn' => 'এএইচকিউ পারমাণবিক সুরক্ষা সেল (এনএসপিসি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0017',
                'user_id' => $user->id,
                'name' => 'AHQ E-EnC`s Branch (Works Department)',
                'name_bn' => 'এএইচকিউ ই-ইন্স শাখা (কর্ম বিভাগ)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0018',
                'user_id' => $user->id,
                'name' => 'HSIA UNDERPASS PROJECT-24 Engr Brigade',
                'name_bn' => 'এইচএসআইএ আন্ডারপাস প্রকল্প-২৪ ইঞ্জিনিয়ার ব্রিগেড',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0019',
                'user_id' => $user->id,
                'name' => 'AHQ Overseas Operation Supervision Cell (OOSC)',
                'name_bn' => 'এএইচকিউ ওভারসিজ অপারেশন সুপারভিশন সেল (ওওএসসি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0020',
                'user_id' => $user->id,
                'name' => 'Al Burhan ',
                'name_bn' => 'আল বুরহান',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0021',
                'user_id' => $user->id,
                'name' => 'Armed Forces Medical College',
                'name_bn' => 'সশস্ত্র বাহিনী মেডিকেল কলেজ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0022',
                'user_id' => $user->id,
                'name' => 'Army Camp (100 Feet Generator)',
                'name_bn' => 'আর্মি ক্যাম্প (১০০ ফুট জেনারেটর)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0023',
                'user_id' => $user->id,
                'name' => 'Army Camp (100 Feet Khal Project)',
                'name_bn' => 'আর্মি ক্যাম্প (১০০ ফুট খাল প্রকল্প)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0024',
                'user_id' => $user->id,
                'name' => 'Army Golf Club',
                'name_bn' => 'আর্মি গলফ ক্লাব',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0025',
                'user_id' => $user->id,
                'name' => 'AFD -02',
                'name_bn' => 'এএফডি-০২',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0026',
                'user_id' => $user->id,
                'name' => 'BAF Shaheen College, Dhaka',
                'name_bn' => 'বিএএফ শাহীন কলেজ, ঢাকা',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0027',
                'user_id' => $user->id,
                'name' => 'BAF Shaheen College, Kurmitola',
                'name_bn' => 'বিএএফ শাহীন কলেজ, কুর্মিটোলা',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0028',
                'user_id' => $user->id,
                'name' => 'Bangladesh Defence Board (Kakrail) (BASB)',
                'name_bn' => 'বাংলাদেশ প্রতিরক্ষা বোর্ড (কাকরাইল) (BASB)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0029',
                'user_id' => $user->id,
                'name' => 'Bangladesh Diesel Plant (BDP)',
                'name_bn' => 'বাংলাদেশ ডিজেল প্ল্যান্ট (BDP)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0030',
                'user_id' => $user->id,
                'name' => 'Bangladesh Institute of Inter Steady (BIISS)',
                'name_bn' => 'বাংলাদেশ ইনস্টিটিউট অফ ইন্টার স্টেডি (BIISS)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0031',
                'user_id' => $user->id,
                'name' => ' Bangladesh International School (BISC) Mohakhali',
                'name_bn' => 'বাংলাদেশ ইন্টারন্যাশনাল স্কুল (BISC) মহাখালী',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0032',
                'user_id' => $user->id,
                'name' => 'Bangladesh Olympic Association (BOA)',
                'name_bn' => 'বাংলাদেশ অলিম্পিক অ্যাসোসিয়েশন (BOA)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0033',
                'user_id' => $user->id,
                'name' => 'Bangladesh Shipping Corporation ',
                'name_bn' => 'বাংলাদেশ শিপিং কর্পোরেশন',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0034',
                'user_id' => $user->id,
                'name' => 'Bangladesh Tea Board',
                'name_bn' => 'বাংলাদেশ চা বোর্ড',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0040',
                'user_id' => $user->id,
                'name' => 'Beximco Holding ',
                'name_bn' => 'বেক্সিমকো হোল্ডিং',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0041',
                'user_id' => $user->id,
                'name' => 'Bilal Trading Pvt Ltd',
                'name_bn' => 'বিলাল ট্রেডিং প্রাইভেট লিমিটেড',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0042',
                'user_id' => $user->id,
                'name' => 'BISC Jalshiri',
                'name_bn' => 'বিআইএসসি জলসিরি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0043',
                'user_id' => $user->id,
                'name' => 'BMDF',
                'name_bn' => 'বিএমডিএফ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0044',
                'user_id' => $user->id,
                'name' => 'BMTF',
                'name_bn' => 'বিএমটিএফ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0045',
                'user_id' => $user->id,
                'name' => 'BN College',
                'name_bn' => 'বিএন কলেজ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0046',
                'user_id' => $user->id,
                'name' => 'BNCC HQ',
                'name_bn' => 'বিএনসিসি সদর দপ্তর',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0047',
                'user_id' => $user->id,
                'name' => 'BNCC Ramna Regiment',
                'name_bn' => 'বিএনসিসি রমনা রেজিমেন্ট',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0048',
                'user_id' => $user->id,
                'name' => 'Brig Gen Mostafa Kamal (Retd)',
                'name_bn' => 'ব্রিগেডিয়ার জেনারেল মোস্তফা কামাল (অবসরপ্রাপ্ত)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0049',
                'user_id' => $user->id,
                'name' => 'BSMR - Permanent Campus',
                'name_bn' => 'বিএসএমআর - স্থায়ী ক্যাম্পাস',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0050',
                'user_id' => $user->id,
                'name' => 'BSMR (A & A U) Tejgoan',
                'name_bn' => 'বিএসএমআর (এ এবং এ ইউ) তেজগাঁও',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0051',
                'user_id' => $user->id,
                'name' => 'BSMR (Maritime University) Mirpur',
                'name_bn' => 'বিএসএমআর (মেরিটাইম ইউনিভার্সিটি) মিরপুর',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0053',
                'user_id' => $user->id,
                'name' => 'BTMC',
                'name_bn' => 'বিটিএমসি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0054',
                'user_id' => $user->id,
                'name' => 'MRT Line-1 Utility Relocation Project (24 Engr)',
                'name_bn' => 'এমআরটি লাইন-১ ইউটিলিটি রিলোকেশন প্রজেক্ট (২৪ ইঞ্জিনিয়ার)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0055',
                'user_id' => $user->id,
                'name' => 'BUP-Chief Planing        ',
                'name_bn' => 'বিইউপি-চিফ প্ল্যানিং',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0056',
                'user_id' => $user->id,
                'name' => 'BUP-Chief Planing-Generator         ',
                'name_bn' => 'বিইউপি-চিফ প্ল্যানিং-জেনারেটর',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0057',
                'user_id' => $user->id,
                'name' => 'BUP-FBS FST',
                'name_bn' => 'বিইউপি-এফবিএস এফএসটি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0058',
                'user_id' => $user->id,
                'name' => 'BUP-FSSS       ',
                'name_bn' => 'বিইউপি-এফএসএসএস',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0059',
                'user_id' => $user->id,
                'name' => 'BUP-Generator',
                'name_bn' => 'বিইউপি-জেনারেটর',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0060',
                'user_id' => $user->id,
                'name' => 'BUP-ICT',
                'name_bn' => 'বিইউপি-আইসিটি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0061',
                'user_id' => $user->id,
                'name' => 'BUP-MT',
                'name_bn' => 'বিইউপি-এমটি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0062',
                'user_id' => $user->id,
                'name' => 'Cantonment Board (Army)',
                'name_bn' => 'ক্যান্টনমেন্ট বোর্ড (সেনাবাহিনী)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0063',
                'user_id' => $user->id,
                'name' => 'Cantonment Board (BAF)',
                'name_bn' => 'ক্যান্টনমেন্ট বোর্ড (বিএএফ)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0064',
                'user_id' => $user->id,
                'name' => 'Cantonment Board (Navy)',
                'name_bn' => 'ক্যান্টনমেন্ট বোর্ড (নৌবাহিনী)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0065',
                'user_id' => $user->id,
                'name' => 'Cantonment Board (Diesel)',
                'name_bn' => 'ক্যান্টনমেন্ট বোর্ড (ডিজেল)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0066',
                'user_id' => $user->id,
                'name' => 'Cantonment Board (Octane)',
                'name_bn' => 'ক্যান্টনমেন্ট বোর্ড (অক্টেন)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0067',
                'user_id' => $user->id,
                'name' => 'Cantt General Hospital (Seraj Khaleda)',
                'name_bn' => 'ক্যান্ট জেনারেল হাসপাতাল (সিরাজ খালেদা)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0068',
                'user_id' => $user->id,
                'name' => 'Capricorns World (Lt. Col Harun)',
                'name_bn' => 'ক্যাপিকর্নস ওয়ার্ল্ড (লে. কর্নেল হারুন)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0069',
                'user_id' => $user->id,
                'name' => 'Center For Medical Education (CME)',
                'name_bn' => 'সেন্টার ফর মেডিকেল এডুকেশন (সিএমই)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0070',
                'user_id' => $user->id,
                'name' => 'Coast Guard (Logistic)',
                'name_bn' => 'কোস্টগার্ড (লজিস্টিক)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0071',
                'user_id' => $user->id,
                'name' => 'Coast Guard HQ-1',
                'name_bn' => 'কোস্ট গার্ড সদর দপ্তর-১',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0072',
                'user_id' => $user->id,
                'name' => 'Coast Guard HQ-2',
                'name_bn' => 'কোস্ট গার্ড সদর দপ্তর-২',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0073',
                'user_id' => $user->id,
                'name' => 'Control General Defence Finance (CGDF)',
                'name_bn' => 'কন্ট্রোল জেনারেল ডিফেন্স ফাইন্যান্স (সিজিডিএফ)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0074',
                'user_id' => $user->id,
                'name' => 'CSD TOWER ',
                'name_bn' => 'সিএসডি টাওয়ার',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0075',
                'user_id' => $user->id,
                'name' => 'CSC-1 (Adhoc)',
                'name_bn' => 'সিএসসি-১ (অ্যাডহক)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0076',
                'user_id' => $user->id,
                'name' => 'CSD Admin Branch',
                'name_bn' => 'সিএসডি অ্যাডমিন শাখা',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0077',
                'user_id' => $user->id,
                'name' => 'CSD Bakery',
                'name_bn' => 'সিএসডি বেকারি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0078',
                'user_id' => $user->id,
                'name' => 'CSD Baridhara',
                'name_bn' => 'সিএসডি বারিধারা',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0079',
                'user_id' => $user->id,
                'name' => 'CSD Captains World-Jahangir Gate',
                'name_bn' => 'সিএসডি ক্যাপ্টেনস ওয়ার্ল্ড-জাহাঙ্গীর গেট',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0080',
                'user_id' => $user->id,
                'name' => 'CSD Cindrella',
                'name_bn' => 'সিএসডি সিন্ড্রেলা',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0081',
                'user_id' => $user->id,
                'name' => 'CSD Exclusive Shop',
                'name_bn' => 'সিএসডি এক্সক্লুসিভ শপ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0082',
                'user_id' => $user->id,
                'name' => 'CSD Farm ',
                'name_bn' => 'সিএসডি ফার্ম',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0083',
                'user_id' => $user->id,
                'name' => 'CSD Filling Station (Generator)',
                'name_bn' => 'সিএসডি ফিলিং স্টেশন (জেনারেটর)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0084',
                'user_id' => $user->id,
                'name' => 'CSD Filling Station (Vehicle)',
                'name_bn' => 'সিএসডি ফিলিং স্টেশন (যানবাহন)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0085',
                'user_id' => $user->id,
                'name' => 'CSD Jibontory CMH',
                'name_bn' => 'সিএসডি জীবনটরি সিএমএইচ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0086',
                'user_id' => $user->id,
                'name' => 'CSD Mirpur Shop',
                'name_bn' => 'সিএসডি মিরপুর শপ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0087',
                'user_id' => $user->id,
                'name' => 'CSD Mahakhali Shop',
                'name_bn' => 'সিএসডি মহাখালী শপ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0088',
                'user_id' => $user->id,
                'name' => 'CSD Operation Branch',
                'name_bn' => 'সিএসডি অপারেশন শাখা',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0089',
                'user_id' => $user->id,
                'name' => 'CSD  Post Office Shop',
                'name_bn' => 'সিএসডি পোস্ট অফিস শপ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0090',
                'user_id' => $user->id,
                'name' => 'CSD Super Store DCS',
                'name_bn' => 'সিএসডি সুপার স্টোর ডিসিএস',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0091',
                'user_id' => $user->id,
                'name' => 'CSD Tess',
                'name_bn' => 'সিএসডি টেস',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0092',
                'user_id' => $user->id,
                'name' => 'CSD Trading Branch',
                'name_bn' => 'সিএসডি ট্রেডিং শাখা',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0093',
                'user_id' => $user->id,
                'name' => 'CSD Ware House-01',
                'name_bn' => 'সিএসডি ওয়্যার হাউস-০১',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0094',
                'user_id' => $user->id,
                'name' => 'CSD Ware House-02',
                'name_bn' => 'সিএসডি ওয়্যার হাউস-০২',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0095',
                'user_id' => $user->id,
                'name' => 'CSD Zia Colony Tess',
                'name_bn' => 'সিএসডি জিয়া কলোনি টেস',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0096',
                'user_id' => $user->id,
                'name' => 'Department of Shipping ',
                'name_bn' => 'শিপিং বিভাগ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0099',
                'user_id' => $user->id,
                'name' => 'DESCO (Agargoan)',
                'name_bn' => 'ডেসকো (আগারগাঁও)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0100',
                'user_id' => $user->id,
                'name' => 'DESCO (Head Office)',
                'name_bn' => 'ডেসকো (প্রধান কার্যালয়)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0101',
                'user_id' => $user->id,
                'name' => 'DESCO (JoarShahara)',
                'name_bn' => 'ডেসকো (জোয়ারশাহারা)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0102',
                'user_id' => $user->id,
                'name' => 'DESCO (Kafrul )',
                'name_bn' => 'ডেসকো (কাফরুল)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0103',
                'user_id' => $user->id,
                'name' => 'DESCO (Monipur)',
                'name_bn' => 'ডেসকো (মণিপুর)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0104',
                'user_id' => $user->id,
                'name' => 'DESCO (Pallabi)',
                'name_bn' => 'ডেসকো (পল্লবী)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0105',
                'user_id' => $user->id,
                'name' => 'DESCO (Rupnagar)',
                'name_bn' => 'ডেসকো (রূপনগর)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0106',
                'user_id' => $user->id,
                'name' => 'DESCO (Shah Ali)',
                'name_bn' => 'ডেসকো (শাহ আলী)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0107',
                'user_id' => $user->id,
                'name' => 'DESCO (Testing & Repairing)',
                'name_bn' => 'ডেসকো (পরীক্ষা ও মেরামত)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0108',
                'user_id' => $user->id,
                'name' => 'DEWL (Navy Dockeyeard)',
                'name_bn' => 'ডিইডব্লিউএল (নৌবাহিনী ডকইয়ার্ড)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0109',
                'user_id' => $user->id,
                'name' => 'DGFI (Project)',
                'name_bn' => 'ডিজিএফআই (প্রকল্প)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0110',
                'user_id' => $user->id,
                'name' => 'Dhaka Cantt Girls Public School & College',
                'name_bn' => 'ঢাকা ক্যান্ট গার্লস পাবলিক স্কুল ও কলেজ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0111',
                'user_id' => $user->id,
                'name' => 'District Defence Board (DASB)',
                'name_bn' => 'জেলা প্রতিরক্ষা বোর্ড (ডিএসবি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0112',
                'user_id' => $user->id,
                'name' => 'Education Cell Army Welfare Trust',
                'name_bn' => 'শিক্ষা সেল আর্মি ওয়েলফেয়ার ট্রাস্ট',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0113',
                'user_id' => $user->id,
                'name' => 'Electricity Genaration Company ',
                'name_bn' => 'বিদ্যুৎ উৎপাদন কোম্পানি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0114',
                'user_id' => $user->id,
                'name' => 'FC (Army) -Pay-1                        ',
                'name_bn' => 'এফসি (সেনাবাহিনী) -পে-১',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0115',
                'user_id' => $user->id,
                'name' => 'FC (Army) -Pay-2',
                'name_bn' => 'এফসি (সেনাবাহিনী) -পে-২',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0116',
                'user_id' => $user->id,
                'name' => 'Financial Management (FiMa)',
                'name_bn' => 'আর্থিক ব্যবস্থাপনা (এফআইএমএ)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0122',
                'user_id' => $user->id,
                'name' => 'Gournadi Textile Project',
                'name_bn' => 'গৌরনদী টেক্সটাইল প্রকল্প',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0123',
                'user_id' => $user->id,
                'name' => 'Grameen Comunication',
                'name_bn' => 'গ্রামীণ যোগাযোগ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0124',
                'user_id' => $user->id,
                'name' => 'Grameen Telecom Trust',
                'name_bn' => 'গ্রামীণ টেলিকম ট্রাস্ট',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0125',
                'user_id' => $user->id,
                'name' => 'Home-71',
                'name_bn' => 'হোম-৭১',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0126',
                'user_id' => $user->id,
                'name' => 'Hasan Enterprise',
                'name_bn' => 'হাসান এন্টারপ্রাইজ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0127',
                'user_id' => $user->id,
                'name' => 'ISPR   ',
                'name_bn' => 'আইএসপিআর',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0128',
                'user_id' => $user->id,
                'name' => 'ISSB',
                'name_bn' => 'আইএসএসবি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0129',
                'user_id' => $user->id,
                'name' => 'JolShiri Project (Generator)',
                'name_bn' => 'জলশিরি প্রকল্প (জেনারেটর)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0130',
                'user_id' => $user->id,
                'name' => 'JolShiri Project',
                'name_bn' => 'জলশিরি প্রকল্প',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0131',
                'user_id' => $user->id,
                'name' => 'KB Petro Chemical Ltd',
                'name_bn' => 'কেবি পেট্রো কেমিক্যাল লিমিটেড',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0132',
                'user_id' => $user->id,
                'name' => 'Kurmitola Golf Club',
                'name_bn' => 'কুর্মিটোলা গলফ ক্লাব',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0133',
                'user_id' => $user->id,
                'name' => 'Kurmitola General Hospital (Generator)',
                'name_bn' => 'কুর্মিটোলা জেনারেল হাসপাতাল (জেনারেটর)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0134',
                'user_id' => $user->id,
                'name' => 'Kurmitola General Hospital ',
                'name_bn' => 'কুর্মিটোলা জেনারেল হাসপাতাল',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0135',
                'user_id' => $user->id,
                'name' => 'Madani Avenue (Project)',
                'name_bn' => 'মাদানী অ্যাভিনিউ (প্রকল্প)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0136',
                'user_id' => $user->id,
                'name' => 'Maj Rashed Latif',
                'name_bn' => 'মেজর রাশেদ লতিফ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0137',
                'user_id' => $user->id,
                'name' => '(DMCBL) The Dhaka Mercantile Co-operative',
                'name_bn' => '(ডিএমসিবিএল) ঢাকা মার্কেন্টাইল কো-অপারেটিভ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0138',
                'user_id' => $user->id,
                'name' => 'Military Estate Office (MEO)',
                'name_bn' => 'মিলিটারি এস্টেট অফিস (এমইও)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0139',
                'user_id' => $user->id,
                'name' => 'Military Land & Cantt (DML & C)',
                'name_bn' => 'মিলিটারি ল্যান্ড অ্যান্ড ক্যান্ট (ডিএমএল অ্যান্ড সি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0140',
                'user_id' => $user->id,
                'name' => 'Ministry of Defence (198 Cantt)',
                'name_bn' => 'প্রতিরক্ষা মন্ত্রণালয় (১৯৮ ক্যান্ট)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0141',
                'user_id' => $user->id,
                'name' => 'Uttara Finance',
                'name_bn' => 'উত্তরা ফাইন্যান্স',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0142',
                'user_id' => $user->id,
                'name' => 'MRT Line-5 Utility Relocation Project (24 Engr)',
                'name_bn' => 'এমআরটি লাইন-৫ ইউটিলিটি রিলোকেশন প্রজেক্ট (২৪ ইঞ্জিনিয়ার)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0143',
                'user_id' => $user->id,
                'name' => 'National Defence College (NDC)',
                'name_bn' => 'ন্যাশনাল ডিফেন্স কলেজ (এনডিসি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0144',
                'user_id' => $user->id,
                'name' => 'National Tele Monit Center (NTMC) (Govt)',
                'name_bn' => 'ন্যাশনাল টেলি মনিট সেন্টার (এনটিএমসি) (সরকারি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0145',
                'user_id' => $user->id,
                'name' => 'National Tele Monit Center (NTMC) (Pvt)',
                'name_bn' => 'ন্যাশনাল টেলি মনিট সেন্টার (এনটিএমসি) (প্রাইভেট)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0146',
                'user_id' => $user->id,
                'name' => 'NSI 100',
                'name_bn' => 'এনএসআই ১০০',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0147',
                'user_id' => $user->id,
                'name' => 'NSI 101',
                'name_bn' => 'এনএসআই ১০১',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0148',
                'user_id' => $user->id,
                'name' => 'Padma  Rail Link  (PBRLP)',
                'name_bn' => 'পদ্মা রেল লিংক (পিবিআরএলপি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0149',
                'user_id' => $user->id,
                'name' => 'Palmal Group of Industries',
                'name_bn' => 'পালমাল গ্রুপ অফ ইন্ডাস্ট্রিজ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0150',
                'user_id' => $user->id,
                'name' => 'Pasport Office (Dept of Immigration and Passport)',
                'name_bn' => 'পাসপোর্ট অফিস (ইমিগ্রেশন অ্যান্ড পাসপোর্ট বিভাগ)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0151',
                'user_id' => $user->id,
                'name' => 'Passport Office (E Project)',
                'name_bn' => 'পাসপোর্ট অফিস (ই প্রজেক্ট)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0152',
                'user_id' => $user->id,
                'name' => 'Payra Bandor Authority',
                'name_bn' => 'পায়রা বন্দর কর্তৃপক্ষ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0153',
                'user_id' => $user->id,
                'name' => 'Proyas School',
                'name_bn' => 'প্রয়াস স্কুল',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0154',
                'user_id' => $user->id,
                'name' => 'Pabna Dist Isamoti River PROJACT',
                'name_bn' => 'পাবনা জেলা ইসামতি নদী প্রকল্প',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0155',
                'user_id' => $user->id,
                'name' => 'RAB Forces',
                'name_bn' => 'র‍্যাব ফোর্সেস',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0156',
                'user_id' => $user->id,
                'name' => 'Rainbow Kindergarden',
                'name_bn' => 'রেইনবো কিন্ডারগার্ডেন',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0157',
                'user_id' => $user->id,
                'name' => 'Rajuk College',
                'name_bn' => 'রাজুক কলেজ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0158',
                'user_id' => $user->id,
                'name' => '4 River Project, Bogura',
                'name_bn' => '৪ নদী প্রকল্প, বগুড়া',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0159',
                'user_id' => $user->id,
                'name' => 'Romizuddin College (Bus)',
                'name_bn' => 'রমিজউদ্দিন কলেজ (বাস)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0160',
                'user_id' => $user->id,
                'name' => 'Romizuddin College (Micro)',
                'name_bn' => 'রমিজউদ্দিন কলেজ (মাইক্রো)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0161',
                'user_id' => $user->id,
                'name' => 'RAOWA CLUB',
                'name_bn' => 'রাওয়া ক্লাব',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0162',
                'user_id' => $user->id,
                'name' => 'Sena Hotel (Radison)',
                'name_bn' => 'সেনা হোটেল (র‍্যাডিসন)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0163',
                'user_id' => $user->id,
                'name' => 'Sena Kalyan Sanghta (SKB)',
                'name_bn' => 'সেনা কল্যাণ সংস্থা (SKB)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0164',
                'user_id' => $user->id,
                'name' => 'Sena Kalyan Sanghta (SKCD)',
                'name_bn' => 'সেনা কল্যাণ সংস্থা (SKCD)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0165',
                'user_id' => $user->id,
                'name' => 'Sena Kalyan Electronic (SKE)',
                'name_bn' => 'সেনা কল্যাণ ইলেকট্রনিক (SKE)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0166',
                'user_id' => $user->id,
                'name' => 'Sena Kalyan Sanghta (SKS  BD-3)',
                'name_bn' => 'সেনা কল্যাণ সংস্থা (এসকেএস বিডি-৩)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0167',
                'user_id' => $user->id,
                'name' => 'Sena Kalyan Sanghta (SKS  BD-6)',
                'name_bn' => 'সেনা কল্যাণ সংস্থা (এসকেএস বিডি-৬)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0168',
                'user_id' => $user->id,
                'name' => 'Sena Kalyan Sanghta (SKS)',
                'name_bn' => 'সেনা কল্যাণ সংস্থা (এসকেএস)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0169',
                'user_id' => $user->id,
                'name' => 'SFC (Army) ',
                'name_bn' => 'এসএফসি (আর্মি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0170',
                'user_id' => $user->id,
                'name' => 'SFC (Dp)',
                'name_bn' => 'এসএফসি (ডিপি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0171',
                'user_id' => $user->id,
                'name' => 'SFC (Navy) ',
                'name_bn' => 'এসএফসি (নৌবাহিনী) ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0172',
                'user_id' => $user->id,
                'name' => 'SFC (Purta)',
                'name_bn' => 'এসএফসি (পুর্ত)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0173',
                'user_id' => $user->id,
                'name' => 'Shaheed Anwar Girls College',
                'name_bn' => 'শহীদ আনোয়ার গার্লস কলেজ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0174',
                'user_id' => $user->id,
                'name' => 'Sheikh Rasel Cantt Public School (JolShiri)',
                'name_bn' => 'শেখ রাসেল ক্যান্ট পাবলিক স্কুল (জল শিরি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0175',
                'user_id' => $user->id,
                'name' => 'Sonali Bank Ltd',
                'name_bn' => 'সোনালী ব্যাংক লি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0176',
                'user_id' => $user->id,
                'name' => 'Streem Global',
                'name_bn' => 'স্ট্রিম গ্লোবাল',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0177',
                'user_id' => $user->id,
                'name' => 'Summit Communication',
                'name_bn' => 'সামিট কমিউনিকেশন',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0178',
                'user_id' => $user->id,
                'name' => 'Summit Power',
                'name_bn' => 'সামিট পাওয়ার',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0179',
                'user_id' => $user->id,
                'name' => 'The Metal Ltd',
                'name_bn' => 'দ্য মেটাল লি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0180',
                'user_id' => $user->id,
                'name' => 'Trust Bank Ltd (Car-Gen)',
                'name_bn' => 'ট্রাস্ট ব্যাংক লিমিটেড (কার-জেন)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0181',
                'user_id' => $user->id,
                'name' => 'Trust Bank Ltd ',
                'name_bn' => 'ট্রাস্ট ব্যাংক লি ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0182',
                'user_id' => $user->id,
                'name' => 'Trust Green City (Project)',
                'name_bn' => 'ট্রাস্ট গ্রিন সিটি (প্রকল্প)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0183',
                'user_id' => $user->id,
                'name' => 'Trust Security (Log Area)',
                'name_bn' => 'ট্রাস্ট সিকিউরিটি (লগ এরিয়া)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0185',
                'user_id' => $user->id,
                'name' => 'Trust Transport Services (Taxi)',
                'name_bn' => 'ট্রাস্ট পরিবহন সেবা (ট্যাক্সি)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0186',
                'user_id' => $user->id,
                'name' => 'DESCO (Kallyanpur)',
                'name_bn' => 'ডেসকো (কল্যাণপুর)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0187',
                'user_id' => $user->id,
                'name' => 'DESCO (Eastern Housing)',
                'name_bn' => 'ডেসকো (ইস্টার্ন হাউজিং)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0188',
                'user_id' => $user->id,
                'name' => 'DESCO (Ibrahimpur)',
                'name_bn' => 'ডেসকো (ইব্রাহিমপুর)',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0190',
                'user_id' => $user->id,
                'name' => '(Jolsiri) Adamjee School & College',
                'name_bn' => '(জলসিঁড়ি) আদমজী স্কুল এন্ড কলেজ',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
            [
                'ucode' => '0191',
                'user_id' => $user->id,
                'name' => 'BUP-FST',
                'name_bn' => 'বিইউপি- এফএসটি',
                'logo' => null,
                'is_vat_applied' => false,
                'vat_rate' => 0,
            ],
        ];

        foreach ($organizations as $organization) {
            Organization::firstOrCreate(
                ['name' => $organization['name']],
                $organization
            );
        }
    }
}