services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:80'
      - '3210:3000'
    volumes:
      - .:/var/www/html
    networks:
      - csd_filling_station_network

networks:
  csd_filling_station_network:
    name: csd_filling_station_network
    driver: bridge
